# Generated by Django 2.2.6 on 2019-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_PIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
